config/routes.rb
EventPublisher::Application.routes.draw do

  get "home/index"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/error', :to => 'home#error', :as => :error

  match 'organizer/:id/emails/csvup' => 'emails#csvup', :as => :csvup
  match 'organizer/:id/emails/emaillist' => 'emails#emaillist', :as => :emailupload, :via => :get
  match 'events/viewevents' => 'events#viewevents', :as => :view_events, :via => :post
  match 'events/selectevents' => 'events#selectevents', :as => :select_events, :via => :get
  match 'events/calanderevents' => 'events#calanderevents', :as => :calander_events, :via => :get
  match 'locations/findlocations' => 'locations#findlocations', :as => :find_locations, :via => :get

  resources :overlays
  match 'overlays' => 'overlays#overlays'
  match 'pictures' => 'overlays#getpictures'
  resources :organizers do
    resources :emails
  
  end
  match 'organizers/:id/emails/:id/destroy' => 'emails#destroy', :as => :emaildelete, :via => :delete
  resources :events
  resources :locations 
     

  root :to => "home#index"
  match "*", :to => "home#error"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @events = Event.find(:all,:conditions => "date >= '#{Date.today}'",:order => "date ASC", :limit => 10)
    @event = Event.find(:first, :conditions => "featured = true")
  rescue => e
       redirect_to(error_path, :notice => "Error: #{e.message}")
  end

  def error

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/error.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "error.html" %>

app/views/home/index.html.erb
<%= javascript_include_tag 'jquery.tweet' %>
<script type="text/javascript">
			$(document).ready(function() {
				$('table').Scrollable(120, 260);
                                $("#twitter_update_list").tweet({
                                  avatar_size: 16,
                                  count: 5,
                                  username: "eventsindublin",
                                  loading_text: "searching twitter..."
        });

                                });
</script>
<div class="fleft">
  <div class="smallleft boxxy bigtop">
    <h2>Welcome to The Dublin Event Publisher</h2>
    <p class="flatbottom">This web site allows Event organizers the ability to enter
        the details of their upcoming events to a central database. The event
        organizer has the ability to store details of their event, maintain
        a list of email contacts and make notifications of new events by
        Twitter and email. Registration is required to begin entering your events.
         <%= link_to 'Registration', new_user_path  %> is simple and straightforward and you'll be
        up and running in no time.
    </p> <br/>
    <p > Events can be searched for and viewed within the application. No registration
        is required to view events. Select the View Events button below to view upcoming
        events in Dublin.
    </p>
    <%= link_to "Event Search",select_events_path , :class => "listings_button" %>
  </div>
<div class="smalltop smallleft boxxy">
  <h2>Featured Event</h2>
  <div class =" smallpad">
   <% if !@event.nil? %>
    <span class="spancontent"><%= @event.title %> on:  <%=  @event.date.strftime("%d %b %Y")%></span><br/>

    @ <%= @event.short_location %>

    <br/>

    This is a <%= @event.cost %> event organized by
    <%= @event.organizer.organization %><br/>

     <%= link_to "more information >>",event_path(@event)  %><br/>
    <% else %>
    <p> There are no featured events at present. If you would like
      your event to appear on this home page please contact us.
    </p>
    <% end %>
  </div>
</div>
</div>
<div class="fleft" style="width:260px;">
   <div class="tinyleft actions">
      <h3>Upcoming Events</h3>
      <div class="borderstyle" style="width:260px">
           <table>
            <thead>
             <tr>
               <th>Title</th>
               <th>Date</th>
               <th></th>
             </tr>
           </thead>
           <% if !@events.nil? %>
           <tbody>
           <% @events.each do |event| %>
           <tr>
            <td><%= event.title %></td>
            <td><%= event.date.strftime("%m/%d/%Y") %></td>
            <td><%= link_to '>>', event  %></td>
          </tr>
          <% end %>
          </tbody>
          <% end %>
          </table>
      </div>
   </div>
  
   
<div id="twitter_div" class="displayboxxy">
      <h3 class="sidebar-title">Twitter Updates</h3>
      <ul id="twitter_update_list"></ul>
      <a href="http://twitter.com/eventsindublin" id="twitter-link" style="display:block;text-align:right;">follow us on twitter</a>
</div>
</div>


<div class="clear"></div>