config/routes.rb
EventPublisher::Application.routes.draw do

  get "home/index"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/error', :to => 'home#error', :as => :error

  match 'organizer/:id/emails/csvup' => 'emails#csvup', :as => :csvup
  match 'organizer/:id/emails/emaillist' => 'emails#emaillist', :as => :emailupload, :via => :get
  match 'events/viewevents' => 'events#viewevents', :as => :view_events, :via => :post
  match 'events/selectevents' => 'events#selectevents', :as => :select_events, :via => :get
  match 'events/calanderevents' => 'events#calanderevents', :as => :calander_events, :via => :get
  match 'locations/findlocations' => 'locations#findlocations', :as => :find_locations, :via => :get

  resources :overlays
  match 'overlays' => 'overlays#overlays'
  match 'pictures' => 'overlays#getpictures'
  resources :organizers do
    resources :emails
  
  end
  match 'organizers/:id/emails/:id/destroy' => 'emails#destroy', :as => :emaildelete, :via => :delete
  resources :events
  resources :locations 
     

  root :to => "home#index"
  match "*", :to => "home#error"

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer(4)      not null, primary key
#  organizer_id :integer(4)      not null
#  title        :string(45)      not null
#  description  :string(255)     not null
#  category_id  :integer(4)      not null
#  date         :string(10)      not null
#  end_date     :string(10)      not null
#  start_time   :integer(4)      not null
#  location_id  :integer(4)      not null
#  cost         :string(4)       not null
#  event_url    :string(255)
#
class Event < ActiveRecord::Base

  urlregex = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
  belongs_to :location
  belongs_to :organizer
  belongs_to :category
  validates :title,  :presence => true,
                     :length   => { :maximum => 50 }
  validates :description, :presence => true
                 
  validates :date,  :presence => true
  validates :end_date,  :presence => true
  validates :start_time,  :presence => true
  validates :category_id,  :presence => true
  validates :location_id,  :presence => true
  validates :event_url,  :presence => true,
      :format   => { :with => urlregex }
  
  validates_with EventDateValidator

  def validate_date
    @start = Date.strptime(self.date,"%d/%m/%Y")
    @end = Date.strptime(self.end_date,"%d/%m/%Y")
    errors.add :date, "End Date Must Be Greater Than Start Date" if (@end < @start)
  end

  def short_location
    self.location.location_name.split(",")[0]
  end
  def short_desc
    (self.description.length > 50) ? (self.description[0..49] + '...') : self.description
  end
  def save
    begin
      super
    rescue => e
      redirect_to error_path, :notice => "error; =#{e.message}"
    end
  end

  def self.setnew(params,organizer)
    @event = Event.new(params)
    @event.fixdatesfromdatepicker(params[:date],params[:end_date])

    @event.organizer_id = organizer.id
    return @event
  end
  def fixdatesfromdatepicker(date,end_date)
    self.date=DateTime.strptime(date,"%m/%d/%Y") if self.date.nil?
    self.end_date=DateTime.strptime(end_date,"%m/%d/%Y") if self.end_date.nil?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate, :only => [:new, :create, :destroy, :edit, :index]
  after_filter :cors_set_access_control_headers

  class StoreSelection
    attr_accessor :date, :category
    include Singleton
  end

  class FullCalander
    attr_accessor :id, :start, :end, :allDay, :url, :title
  end
  
  def new
    @event = Event.new()
    @locations = Location.all
    @costs = ["Free","Paid"]
    @hours = ["7","8","9","10","11","12","13","14","15","16","17","18","19","20"]
    @mins = ["00","15","30","45"]
    @categories = Category.all
    @signed_in_user = current_user
    @organizer = Organizer.find_by_user(@signed_in_user.account)
    @event.organizer = @organizer
    @event.location_id = @organizer.primary_event_location
    @event.event_url = @organizer.event_home_page
  end

  def create
    @organizer = Organizer.find_by_user(current_user.account)
    @event = Event.setnew(params[:event],@organizer)
    @send_tweet = params[:twitter][:tweet]
    
    @locations = Location.all
    @costs = ["Free","Paid"]
    @hours = ["7","8","9","10","11","12","13","14","15","16","17","18","19","20"]
    @mins = ["00","15","30","45"]
    @categories = Category.all
    
      respond_to do |format|
        if @event.save
         format.html {
          TwitterSend.new(@event) if @send_tweet == 'yes' ## maybe should be singleton ?? only if same handle
          @organizer.emails.each do
            | em |
              UserMailer.event_email(@event,em.email).deliver
          end
          redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :event => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
    if signed_in?
      @organizer = Organizer.find_by_user(current_user.account)
    end
    respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @event.to_xml( :skip_instruct => true, :except => [:id,:featured,:organizer_id,:location_id,:category_id,:updated],:include => :location )
     }
      format.json  { render :json => @event.to_json( :skip_instruct => true, :except => [:id,:featured,:organizer_id,:location_id,:category_id,:updated],:include => :location )
     }
    end
        
  end
  
  def detail
    @event = Event.find(params[:id])
  end
  
  def index
    @organizer = Organizer.find_by_user(current_user.account)
    @events = Event.find(:all, :conditions => "organizer_id = #{@organizer.id}")
   
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.json  { render :json => @events }
    end
  end

def selectevents
    @date = Date.today
    begin
      @events = Event.find(:all, :conditions => "date >= '#{@date}'" , :order => 'date' )
    rescue => e
      redirect_to(error_path, :notice => "Error: #{e.message}")
    end
    @dateselect = ["Week","1 Month","2 Months"]
    @categories = Category.all
    @store = StoreSelection.instance
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events.to_xml( :skip_instruct => true, :except => [:id,:featured,:organizer_id,:location_id,:category_id,:updated],:include => :location )
     }
      format.json  { render :json => @events.to_json( :skip_instruct => true, :except => [:id,:featured,:organizer_id,:location_id,:category_id,:updated],:include => :location )
     }
    end
  end

  def viewevents
    @date = Date.today
    @date = @date.strftime('%Y-%m-%d %H:%M:%S')
    @selectDate = Date.today.to_time.advance( :weeks => 1) 
#    @selectDate = Date.today.to_time.advance( :weeks => 1) if params[:store][:date] =="Week"
#    @selectDate = Date.today.to_time.advance( :months => 1) if params[:store][:date] =="1 Month"
#    @selectDate = Date.today.to_time.advance( :months => 2) if params[:store][:date] =="2 Months"
#    @selectDate = @selectDate.to_date
#    @selectDate = @selectDate.strftime('%Y-%m-%d %H:%M:%S')
    @events=Event.find(:all, :conditions => "date >= '#{@date}' and date <= '#{@selectDate}'" , :order => 'date')
    @dateselect = ["Week","1 Month","2 Months"]
    @categories = Category.all
    @store = StoreSelection.instance

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.json  { render :json => @events }
    end
  end

  def calanderevents
    @date = Date.today
    @date = @date.strftime('%Y-%m-%d %H:%M:%S')
    @selectDate = Date.today.to_time.advance( :weeks => 1)
    @events=Event.find(:all, :conditions => "date >= '#{@date}'", :order => 'date')
#    @events=Event.find(:all, :conditions => "date >= '#{@date}' and date <= '#{@selectDate}'" , :order => 'date')
    @calevents = []
    @events.each do | event |
      calevent = FullCalander.new()
      calevent.id = event.id
      calevent.title = event.title
      calevent.start = event.date.strftime('%Y-%m-%d %H:%M:%S')
      calevent.end = event.end_date.strftime('%Y-%m-%d %H:%M:%S')
      calevent.url = event.event_url
      calevent.allDay = false
      @calevents << calevent
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @calevents }
      format.json  { render :json => @calevents }
    end
  end

  def edit
    @event = Event.find(params[:id])
    @organizer = Organizer.find(@event.organizer_id) ## raise exception if signed in not organizer
    @locations = Location.all
    @costs = ["Free","Paid"]
    @categories = Category.all
  end

  def update
    @event = Event.find(params[:id])

    params[:event][:date]=DateTime.strptime(params[:event][:date],"%d/%m/%Y") if params[:event][:date].length == 10
    params[:event][:end_date]=DateTime.strptime(params[:event][:end_date],"%d/%m/%Y") if params[:event][:end_date].length == 10

    @organizer = Organizer.find(@event.organizer_id)
    @locations = Location.all
    @costs = ["Free","Paid"]
    @categories = Category.all
    if @event.update_attributes(params[:event])
      flash[:success] = "Event updated."
      redirect_to events_path
    else
      @title = "Edit Event"
      render 'edit'
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end

  private

    def authenticate
      deny_access unless signed_in?
    end
    
    # For all responses in this controller, return the CORS access control headers.

    def cors_set_access_control_headers
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Allow-Methods'] = 'GET'
        headers['Access-Control-Allow-Headers'] = %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(',')
        headers['Access-Control-Max-Age'] = "1728000"
    end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

  
<script  type="text/javascript">
        $(document).ready(function () {    
        $("#event_organizer_id").hide();      
        $("#event_date").datepicker({dateFormat: 'mm/dd/yy'});
        $("#event_end_date").datepicker({dateFormat: 'mm/dd/yy'});
         $("#event_date").change( function(){
           var sdate = $("#event_date").val();
           $("#event_end_date").val(sdate);
           $('#event_start_time').focus();
         });
        });


</script>

<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field fleft">
  <label>Select Location </label><br/>
  <%=  collection_select(:event, :location_id, @locations, :id, :location_name, {:include_blank => 'Please Select' }) %>
  
  </div>
  
<div class="clear"></div>
  <div class="field fleft">
    <%= f.label :title %><br />
    <%= f.text_field :title , :size => 50 %>
  </div>
<div class="field fleft">
  <label>Select Category </label><br/>
  <%=  collection_select(:event, :category_id, @categories, :id, :category_name, {:include_blank => 'Please Select' }) %>
  </div>
 <div class='clear'></div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5 %>
  </div>
  
  <div class="field fleft">
    <%= f.label :date %><br />
    <%= f.text_field :date , :size => 10 %>
  </div>
  <div class="field fleft padleft">
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time , :size => 10 , :class => 'time'%>
  </div>
  <div class="field fleft padleft">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date , :size => 10 %>
  </div>

  <div class="field fleft padleft">
    <%= f.label :event_url %><br />
    <%=  f.text_field :event_url  %>
    <img alt="info" id ="urlinfo" title="Enter URL address including http - e.g. http://www.ncirl.ie" src="/images/information.jpg" />
  </div>

  <div class="field fleft padleft">
    <%= f.label :cost %><br />
  <%=  select(:event,:cost,@costs) %>
  </div>
 <div class="fleft padleft">
   Send Tweet ? <br />
  yes<%=  radio_button("twitter", "tweet", "yes",:checked => true) %>
  no<%=  radio_button("twitter", "tweet", "no") %>
 </div>


  <%= f.text_field :organizer_id , :size => 10 %>

  <div class="clear"></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/detail.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "detail.html" %>

app/views/events/edit.html.erb
 <%= render 'layouts/organizer_navigation' %>
<div class="clear"></div>
<div class="bigleft">
<h3>Update Event Details</h3>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<%= javascript_include_tag :defaults %>

 <%= render 'layouts/organizer_navigation' %>
<div class="clear"></div>
<div class="bigleft">
  <h3>My Events</h3>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td style="width: 350px;"><%= (event.description.length > 50) ? (event.description[0..49] + '...') : event.description %></td>
    <td><%= event.date.strftime("%m/%d/%Y") %></td>
    <td><%= event.short_location %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>
</div>
 <div class="clear"></div>

app/views/events/new.html.erb
 <%= render 'layouts/organizer_navigation' %>
 <div class="clear"></div>
 <div class="fleft bigleft">
 <h3>Create New Event</h3>
<%= render 'form' %>

<%= link_to 'Back', events_path %>
 </div>
 <div class ="clear"></div>
 

app/views/events/selectevents.html.erb
<%= render 'layouts/event_select' %>

app/views/events/show.html.erb
<%= stylesheet_link_tag 'tooltip' %>

<script type="text/javascript">
    var map = null;
    var geocoder = null;
    var markerOptions =null;
    var eventlon = null;
    var eventlat = null;
    var iconList = { eating: "yellow", hotel: "orange",convenience: "brown", pub: "green", transport: "gray", atm: "purple", supermarket: "white", bikerental: "blue"};

    function initialize() {
      if (GBrowserIsCompatible()) {
        
        // Create our "tiny" marker icon
        var tinyIcon = new GIcon();
        tinyIcon.image = "/images/mm_20_yellow.png";
        tinyIcon.shadow = "/images/mm_20_shadow.png";
        tinyIcon.iconSize = new GSize(12, 20);
        tinyIcon.shadowSize = new GSize(22, 20);
        tinyIcon.iconAnchor = new GPoint(6, 20);
        tinyIcon.infoWindowAnchor = new GPoint(5, 1);

        // Set up our GMarkerOptions object
        markerOptions = { icon:tinyIcon };
        map = new GMap2(document.getElementById("map_canvas"));
        map.setCenter(new GLatLng(53.348867,-6.243162), 13);
        geocoder = new GClientGeocoder();
      }
    }
    function loadMaps() {
             google.load("maps", "2.x", {"callback" : initialize});
    }

    function loadScript() {
      var script = document.createElement("script");
      script.src = "https://www.google.com/jsapi?key=<%=@googleapi%>&callback=loadMaps";
      script.type = "text/javascript";
      document.getElementsByTagName("head")[0].appendChild(script);
      }
      
    function clearOverlayDetails() {
        map.clearOverlays();
      }

    function locateBusiness(address,title,lat,longit) {
        map.clearOverlays();
        $('div#rightbaroverlay').show();
        eventlon = longit;
        eventlat = lat;
        point = new GLatLng(lat,longit);
        marker = new GMarker(point);
        map.addOverlay(marker);
        map.addControl(new GLargeMapControl());
        map.setCenter(point, 15);
        GEvent.addListener(marker, "click", function() {
          marker.openInfoWindowHtml(address + '<br>' +
          '<b>Event:</b> ' + title);
        });
        marker.openInfoWindowHtml(address + '<br>' +
          '<b>Event:</b> ' + title);
      }
      function placeOverlays(name,amenity,lat,longit) {

        point = new GLatLng(lat,longit);
        markerOptions.title = amenity + ' ' + name;
        markero = new GMarker(point,markerOptions);
        GEvent.addListener(markero, "click", function() {
          marker.openInfoWindowHtml(name + '<br>' +
          '<b>Amenity:</b> ' + amenity);
        });
        map.addOverlay(markero);
      }

  $(document).ready(function () {
        window.onload = loadScript;
      
        $(".tooltips").hover(
			function() { $(this).contents("span:last-child").css({ display: "block" }); },
			function() { $(this).contents("span:last-child").css({ display: "none" }); }
		);

	$(".tooltips").mousemove(function(e) {
			var mousex = e.pageX + 10;
			var mousey = e.pageY + 5;
			$(this).contents("span:last-child").css({  top: mousey, left: mousex });
		});

        $("#QRCODE").attr({ src: "http://api.qrserver.com/v1/create-qr-code/?data='http://events-store.appspot.com/event/<%= @event.id %>'&amp",
          title: "",alt: "QR Code"});

        if(('#QRCODE').length > 0) {
          console.log("image exists");
        } else {
          alert("image doesn't exist");
        }

        $('div#rightbaroverlay').hide();
      
        $('div#overlaydistance input:radio[name=overlay]').change(function() {
          var rangeshow = this.value;
          if (rangeshow == "0.1") 
             {
               map.closeInfoWindow();
               map.setCenter(point,17);
             }
           else {
             map.closeInfoWindow();
             map.setCenter(point,16);
           }
          
        });

        $("button#removeoverlay").click(function (e) {
          e.preventDefault();
          clearOverlayDetails();
        });

        $("div#overlays button").click(function (e) {
                e.preventDefault(); /* prevents form from being submitted */
                var dist = $('div#overlaydistance input:radio[name=overlay]:checked').val()
                $.ajax({
                    type: "Get",
                    url: '/overlays.json',
                    data: { value: this.textContent, distance: dist, lon: eventlon, lat: eventlat},
                    dataType: "json",
                    success: function (response) {
                        var overlays = response;
                        var ic = iconList[(this.data.split("&")[0].split("=")[1]).replace("+","")];
                        var imageText = "/images/mm_20_" + ic + ".png";
                        markerOptions.icon.image = imageText;
                        for (var i=0; i<overlays.length; i++)
                          {
                            var lat = overlays[i].overlay.lat;
                            var lon = overlays[i].overlay.lon;
                            var name = overlays[i].overlay.name;
                            var amenity = overlays[i].overlay.amenity;
                            placeOverlays(name,amenity,lat,lon);
                          }
                          point = new GLatLng(eventlat,eventlon);
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) { 
                      // handle error
                      var i = 0;
                    }
                });
            });
});
</script>

<% if signed_in? %>
 <%= render 'layouts/organizer_navigation' %>
<% end  %>
<div class="clear"></div>
<div class="bigleft"><h3>Events Details</h3></div>
<div id="showevent" class ="fleft bigleft">
  
  <span class="spancontent"><%= @event.title + " on: " + @event.date.strftime("%d %b %Y")%></span><br/>
  <span class ="spanlocation">Show event
  <%= link_to_function 'location', "locateBusiness(\'#{@event.location.location_name}\',\'#{@event.title}\',#{@event.location.geo_lat},#{@event.location.geo_long})" %>
  </span>
  <br/>
  <span class="spancontent">Description</span>
  <p class="smallerpara">
  [<%= @event.description %>]</p><br/>
  This is a <%= @event.cost %> event organized by<br/>
  <%= @event.organizer.organization %><br/>
  [<a href="mailto:<%= @event.organizer.email %>"> email</a>] [
  <%= link_to  "event URL",@event.event_url, :remote => true %>]<br/>
  <div class="tooltips"style="width: 100px;">
  <img id="QRCODE" height="100" width="100"/>
  <p class="tiny" title="">Right click to save QR Code</p>
  <span class="tools tooltip-style1">
    Use this QR code in any marketing material to allow users save this event to their smartphone</span>
  </div>
  </div>

<div class="fleft">
 <div id="map_canvas" class="smalltop"style="margin-left: 20px; width: 400px; height: 400px; float: left;"></div>

 <div id="rightbaroverlay" class="fleft">
 <div id="overlaydistance" class=" padleft">
   Facilities Within  <br />  
  100<%=  radio_button_tag("overlay", "0.1") %>
  500<%=  radio_button_tag("overlay", "0.5",:checked => true) %>(mtrs)
 </div>
 <div id="overlays" >
  <button  id="overlay">eating</button><img class="icons" src ="/images/mm_20_yellow.png" alt=" map icon"/>
  <button  id="overlay">hotel</button><img class="icons" src ="/images/mm_20_orange.png" alt=" map icon"/>
  <button  id="overlay">transport</button><img class="icons" src ="/images/mm_20_gray.png" alt=" map icon"/>
  <button  id="overlay">atm</button><img class="icons" src ="/images/mm_20_purple.png" alt=" map icon"/>
  <button  id="overlay">convenience</button><img class="icons" src ="/images/mm_20_brown.png" alt=" map icon"/>
  <button  id="overlay">supermarket</button><img class="icons" src ="/images/mm_20_white.png" alt=" map icon"/>
  <button  id="overlay">pub</button><img class="icons" src ="/images/mm_20_green.png" alt=" map icon"/>
  <button  id="overlay">bike rental</button><img class="icons" src ="/images/mm_20_blue.png" alt=" map icon"/>
 </div>
 <div id="clearoverlay" >
  <button  id="removeoverlay">Clear</button>
 </div>
</div>
 
</div>
<div class="clear"></div>
<div class="bigleft">
<% if !signed_in? %>
 <%= link_to "Back to Event Search", select_events_path %>
<% end  %>
 </div>

app/views/events/viewevents.html.erb
<%= render 'layouts/event_select' %>