config/routes.rb
EventPublisher::Application.routes.draw do

  get "home/index"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/error', :to => 'home#error', :as => :error

  match 'organizer/:id/emails/csvup' => 'emails#csvup', :as => :csvup
  match 'organizer/:id/emails/emaillist' => 'emails#emaillist', :as => :emailupload, :via => :get
  match 'events/viewevents' => 'events#viewevents', :as => :view_events, :via => :post
  match 'events/selectevents' => 'events#selectevents', :as => :select_events, :via => :get
  match 'events/calanderevents' => 'events#calanderevents', :as => :calander_events, :via => :get
  match 'locations/findlocations' => 'locations#findlocations', :as => :find_locations, :via => :get

  resources :overlays
  match 'overlays' => 'overlays#overlays'
  match 'pictures' => 'overlays#getpictures'
  resources :organizers do
    resources :emails
  
  end
  match 'organizers/:id/emails/:id/destroy' => 'emails#destroy', :as => :emaildelete, :via => :delete
  resources :events
  resources :locations 
     

  root :to => "home#index"
  match "*", :to => "home#error"

end

app/views/layouts/_event_select.html.erb
<div class="fleft selectionbox">
  <h3>Events </h3>
  <%= form_for @store, :as => :store, :url => view_events_path, :html => {:method => :post} do |f| %>
  <div class="field">
      <label>Select Category </label><br/>
      <%=  collection_select( :store, :category, @categories, :id, :category_name, {:include_blank => 'Please Select' }) %>
  </div>
  <div class="field ">
      <label>In The Next </label><br/>
      <%=  select(:store,:date,@dateselect) %>
  </div>
  <div class="actions">
   <input id="event_submit" name="commit" type="submit" value="Select" />

  </div>
  <% end %>
  <a href="#" id="gridview" class="buttsel">Grid View</a>
  <a href="#" id="calview" class="buttsel">Calendar View</a>
</div>
  <div id="grid" class="fleft smallleft bigtop">
   <table>
   <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date</th>
    <th>Location</th>  
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td style="width: 350px;"><%= event.short_desc %></td>
    <td><%= event.date.strftime("%m/%d/%Y") %></td>
    <td><%= event.short_location %></td>
    <td><%= link_to 'Show', event %></td>
  </tr>
<% end %>
</table> 
  </div>

<div id="calendar" style="float:left;width: 820px;margin: 0 auto;"></div>
<div class="clear"></div>
<script>

                var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
                var url = document.URL.split('/');
                urlpost='http://'+url[2]+'/events/calanderevents.json'


		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			editable: false,
			events: urlpost
		});
                 $(document).ready(function(){
                   $('#calendar').hide();
                   $('#gridview').hide();
                   $("#calview").click(function(){
                     $('#calendar').show();
                     $('#grid').hide();
                     $('#calview').hide();
                     $('#gridview').show();
                    });
                    $("#gridview").click(function(){
                     $('#calendar').hide();
                     $('#grid').show();
                     $('#calview').show();
                     $('#gridview').hide();
                    });
                 });

</script>

app/views/layouts/_googleV2api.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key=<%= @googleapi %>&amp;callback=initialize" type="text/javascript"></script>

app/views/layouts/_googleapi.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>

app/views/layouts/_organizer_navigation.html.erb
<div class="nav mainnav bigleft biggerfont smalltop">
 
    <ul>
      <li><%= link_to "New Event", new_event_path , :class => current_class?(new_event_path)%></li>
      <li><%= link_to "My Contacts", organizer_emails_path(@organizer), :class => current_class?(organizer_emails_path(@organizer))  %></li>
      <li><%= link_to "My Events", events_path ,:class => current_class?(events_path) %></li>
      <li><%= link_to "My Account", edit_organizer_path(@organizer), :class => current_class?(edit_organizer_path(@organizer)) %></li>
      <li><%= link_to 'New Location', new_location_path ,:class => current_class?(new_location_path) %></li>
    </ul>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventPublisher</title>

  <%= stylesheet_link_tag 'index' %>
  <%= stylesheet_link_tag 'fullcalendar' %>
  <%= stylesheet_link_tag 'fullcalendar.print' %>
  <%= javascript_include_tag 'jquery-1.4.1' %>
  <%= javascript_include_tag 'jquery.timepicker' %>
  <%= javascript_include_tag 'fullcalendar.min' %>
  <script type="text/javascript" src="http://www.webtoolkit.info/djs/webtoolkit.scrollabletable.js"></script>
  <script type="text/javascript" src="http://www.webtoolkit.info/djs/webtoolkit.jscrollable.js"></script>

  <%= csrf_meta_tag %>
  <script type="text/javascript">
  jQuery.noConflict();
  var $ = jQuery;
  </script>
  <script type="text/javascript">
    $(document).ready(function(){
  // Reset Font Size
  var originalFontSize = $('html').css('font-size');
  $(".resetFont").click(function(){
  $('html').css('font-size', originalFontSize);
  });
  // Increase Font Size
  $(".increaseFont").click(function(){
  	var currentFontSize = $('html').css('font-size');
 	var currentFontSizeNum = parseFloat(currentFontSize, 10);
    var newFontSize = currentFontSizeNum*1.2;
	$('html').css('font-size', newFontSize);
	return false;
  });
  // Decrease Font Size
  $(".decreaseFont").click(function(){
  	var currentFontSize = $('html').css('font-size');
 	var currentFontSizeNum = parseFloat(currentFontSize, 10);
    var newFontSize = currentFontSizeNum*0.8;
	$('html').css('font-size', newFontSize);
	return false;
  });
});

  </script>
</head>
<body >
<div id="container">
      <div class="header">  
        
        <div class="fleft">
           <%= image_tag("tccd.jpg", :alt => "Event Publisher", :class => "round fleft") %>
        </div>
         <h1 id="titlehead" class="fleft">Dublin Event Publisher</h1>
         <div class="nav fleft topnav">
          <ul>
            <li><%= link_to "Home", '/' %></li>
            <li><%= link_to "Help", '#' %></li>
            <li><%= link_to "Register", new_user_path %></li>
             <% if signed_in? %>
            <li><%= link_to "Sign out ", signout_path, :method => :delete %></li>
            welcome [<%= link_to current_user.account, events_path %>]
            <% else %>
            <li><%= link_to "Sign in", new_session_path %></li>

            <% end %>
          </ul>
        </div>
        
      </div>
      <div class="clear"></div>
      <div class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>


        <%= yield %>
      
      <div class="smalltop">
          <span>  Text Size: </span>
          <a href="#" class="increaseFont">Larger</a>
          <a href="#" class="decreaseFont">Smaller</a>
          <a href="#" class="resetFont">Reset</a>
      </div>
     </div>
    </div>
 <%= debug(params) if Rails.env.development? %>

</body>
</html>